arrow/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()

# API
router.register(r'users', views.UsersViewSet)
router.register(r'products', views.ProductsViewSet)


urlpatterns = [
    # REST framework
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Authentication
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logouts'),

    # Main Page
    path('', views.home_view),
    path('portfolio', views.portfolio_view),

    # User
    path('addUser', views.addUser),
    path('showUsers/', views.showUsers),
    path('editUser/<int:id>', views.editUser),
    path('updateUser/<int:id>', views.updateUser),
    path('deleteUser/<int:id>', views.destroyUser),

    # Product
    path('addProduct', views.addProduct),
    path('showProducts/', views.showProducts),
    path('editProduct/<int:id>', views.editProduct),
    path('updateProduct/<int:id>', views.updateProduct),
    path('deleteProduct/<int:id>', views.destroyProduct),
]

crud/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # Django-Jet
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),

    # Default
    path('admin/', admin.site.urls),
    path('', include("arrow.urls")),
]

arrow/models.py
from django.db import models


class User(models.Model):
    First_Name = models.CharField(max_length=100)
    Last_Name = models.CharField(max_length=100)
    Email = models.EmailField()
    Contact = models.CharField(max_length=10)

    class Meta:
        db_table = "User"

    def __str__(self):
        return self.First_Name + ' ' + self.Last_Name


class Product(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products", null=True, blank=True)
    Product_Category = models.CharField(max_length=50)
    Product_Name = models.CharField(max_length=50)

    class Meta:
        db_table = "product"

arrow/forms.py
from django import forms
from .models import *


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

arrow/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework import viewsets, permissions, filters
from rest_framework.pagination import PageNumberPagination

from .forms import *
from .serializers import *


# Authentication
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:
        form = UserCreationForm()
    return render(request, 'arrow/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'arrow/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')


# Main Page
def home_view(request):
    return render(request, 'arrow/home.html')


def portfolio_view(request):
    return render(request, 'arrow/portfolio.html')


# User
def addUser(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/showUsers')
            except:
                pass
    else:
        form = UserForm()
    return render(request, 'arrow/addUser.html', {'form': form})


def showUsers(request):
    if request.user.is_authenticated:
        sort = request.GET.get('sort', '')
        desc = request.GET.get('desc', False)
        user = User.objects.all()

        # Getting search request
        ctx = {}
        url_parameter = request.GET.get("q")

        if url_parameter:
            users = user.filter(First_Name__istartswith=url_parameter)
        else:
            users = user

        # sorting
        if sort:
            if desc:
                users = users.order_by("-" + sort)

            else:
                users = users.order_by(sort)

        # Pagination
        page = request.GET.get('page', 1)

        paginator = Paginator(users, 8)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)

        ctx["desc"] = desc
        ctx["users"] = users
        ctx["q"] = url_parameter
        ctx["sorts"] = sort

        # ajax call
        if request.is_ajax():
            html = render_to_string(
                template_name="arrow/showUsersfile.html",
                context={'desc': desc, 'users': users, 'q': url_parameter, 'sorts': sort}
            )

            data_dict = {"html_from_view": html}
            return JsonResponse(data=data_dict, safe=False)

        return render(request, "arrow/showUsers.html", context=ctx)
    else:
        return redirect('/')


def editUser(request, id):
    if request.user.is_authenticated:
        user = User.objects.get(id=id)
        return render(request, 'arrow/editUser.html', {'user': user, 'id': id})
    else:
        return redirect('/')


def updateUser(request, id):
    if request.user.is_authenticated:
        user = User.objects.get(id=id)
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect("/showUsers")
        return render(request, 'arrow/editUser.html', {'user': user})
    else:
        return redirect('/')


def destroyUser(request, id):
    if request.user.is_authenticated:
        user = User.objects.get(id=id)
        user.delete()
        return redirect("/showUsers")
    else:
        return redirect('/')

# Product
def addProduct(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/showProducts')
            except:
                pass
    else:
        form = ProductForm()
    return render(request, 'arrow/addProduct.html', {'form': form})


def showProducts(request):
    if request.user.is_authenticated:
        products = Product.objects.all()

        # Pagination
        page = request.GET.get('page', 1)

        paginator = Paginator(products, 8)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        return render(request, "arrow/showProducts.html", {'products': products})

    else:
        return redirect('/')


def editProduct(request, id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)
        return render(request, 'arrow/editProduct.html', {'product': product, 'id': id})
    else:
        return redirect('/')


def updateProduct(request, id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)

        if request.method == "POST":
            form = ProductForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
                return redirect("/showProducts")
        form = ProductForm(instance=product)

        return render(request, 'arrow/editProduct.html', {'product': form, 'id': id})
    else:
        return redirect('/')

def destroyProduct(request, id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)
        product.delete()
        return redirect("/showProducts")
    else:
        return redirect('/')


# Rest Framework
class StandardResultsSetPagination(PageNumberPagination):
    page_size = 3
    page_size_query_param = 'page_size'
    max_page_size = 1000


class UsersViewSet(viewsets.ModelViewSet):
    pagination_class = StandardResultsSetPagination
    queryset = User.objects.all()
    serializer_class = UsersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['^First_Name', '^Last_Name']
    ordering_fields = ['First_Name', 'Last_Name']


class ProductsViewSet(viewsets.ModelViewSet):
    pagination_class = StandardResultsSetPagination
    queryset = Product.objects.all()
    serializer_class = ProductsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['^Product_Category', '^Product_Name']
    ordering_fields = ['Product_Category', 'Product_Name']

arrow/templates/arrow/addProduct.html
{% extends "base.html" %}
{% load i18n  static %}


{% block header %}

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Arrow</a>
      </div>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
              <li><a href="/showProducts">Products</a></li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        {% endif %}
    </div>
  </nav>

{% endblock header %}


{% block content %}
        <form method="POST" class="post-form" action="/addProduct">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4"><h3>Enter Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Select User:</label>
                    <div class="col-sm-4">
                        {{ form.User }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Product Category:</label>
                    <div class="col-sm-4">
                        {{ form.Product_Category }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Product Name:</label>
                    <div class="col-sm-4">
                        {{ form.Product_Name }}
                    </div>
                </div>
                <br>
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </form>
{% endblock content %}

arrow/templates/arrow/addUser.html
{% extends "base.html" %}
{% load i18n  static %}


{% block header %}

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Arrow</a>
      </div>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
              <li><a href="/showUsers">Users</a></li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        {% endif %}
    </div>
  </nav>

{% endblock header %}


{% block content %}
        <form method="POST" class="post-form" action="/addUser">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4"><h3>Enter Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">First Name:</label>
                    <div class="col-sm-4">
                        {{ form.First_Name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Last Name:</label>
                    <div class="col-sm-4">
                        {{ form.Last_Name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Email:</label>
                    <div class="col-sm-4">
                        {{ form.Email }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Contact:</label>
                    <div class="col-sm-4">
                        {{ form.Contact }}
                    </div>
                </div>
                <br>
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </form>
{% endblock content %}

arrow/templates/arrow/editProduct.html
{% extends "base.html" %}
{% load i18n  static %}


{% block header %}

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Arrow</a>
      </div>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
              <li><a href="/showProducts">Products</a></li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        {% endif %}
    </div>
  </nav>

{% endblock header %}


{% block content %}
        <form method="POST" class="post-form" action="/updateProduct/{{id}}">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Update Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Select User:</label>
                        {{ product.User }}
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Product Category:</label>
                        {{ product.Product_Category }}
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Product Name:</label>
                        {{ product.Product_Name }}
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </div>
            </div>
        </form>
{% endblock content %}

arrow/templates/arrow/editUser.html
{% extends "base.html" %}
{% load i18n  static %}


{% block header %}

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Arrow</a>
      </div>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
              <li><a href="/showUsers">Users</a></li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        {% endif %}
    </div>
  </nav>

{% endblock header %}


{% block content %}
        <form method="POST" class="post-form" action="/updateUser/{{user.id}}">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Update Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">First Name:</label>
                    <div class="col-sm-4">
                        <input type="text" name="First_Name" id="id_First_Name" required maxlength="100" value="{{ user.First_Name }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Last Name:</label>
                    <div class="col-sm-4">
                        <input type="text" name="Last_Name" id="id_Last_Name" required maxlength="100" value="{{ user.Last_Name }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Email:</label>
                    <div class="col-sm-4">
                        <input type="email" name="Email" id="id_Email" required maxlength="254" value="{{ user.Email }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Contact:</label>
                    <div class="col-sm-4">
                        <input type="text" name="Contact" id="id_Contact" required maxlength="10" value="{{ user.Contact }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </div>
            </div>
        </form>
{% endblock content %}

arrow/templates/arrow/home.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}

{% if user.is_authenticated %}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex flex-column justify-content-end align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Welcome to <span style="color:#47bac1" >ARROW TECH</span></h2>
          <p class="animate__animated fanimate__adeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
          <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
          <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
      </defs>
      <g class="wave1">
        <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)"></use>
      </g>
      <g class="wave2">
          <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)"></use>
      </g>
      <g class="wave3">
          <use xlink:href="#wave-path" x="50" y="9" fill="#fff">,</use>
      </g>
    </svg>

  </section>
            <!-- End Hero -->
  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="section-title" data-aos="zoom-out">
          <h2>About</h2>
          <p>Who we are</p>
        </div>

        <div class="row content" data-aos="fade-up">
          <div class="col-lg-6">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
              <li><i class="ri-check-double-line"></i> Duis aute irure dolor in reprehenderit in voluptate velit</li>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
            </ul>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0">
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <a href="#" class="btn-learn-more">Learn More</a>
          </div>
        </div>

      </div>
    </section>
    <!-- End About Section -->
  </main>
{% else %}
    <br/>
    <br/>
    <h1 align="center">Login in order to get full Access!!</h1>
{% endif %}

{% endblock content %}

arrow/templates/arrow/index.html
{% extends "base.html" %}
{% load i18n  static %}


{% block content %}
        <form method="POST" class="post-form" action="/signup">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4"><h3>Enter Details</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">First Name:</label>
                    <div class="col-sm-4">
                        {{ form.First_Name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Last Name:</label>
                    <div class="col-sm-4">
                        {{ form.Last_Name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Email:</label>
                    <div class="col-sm-4">
                        {{ form.Email }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Contact:</label>
                    <div class="col-sm-4">
                        {{ form.Contact }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </form>
{% endblock content %}

arrow/templates/arrow/login.html
{% extends "base.html" %}
{% load i18n  static %}


{% block content %}
    <form method="post" class="post-form">
    {% csrf_token %}
    <div class="container">
            <br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Log In</h3>
    </div>
  </div>
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
            <br/>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
            <br/>
            <br/>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                Don't have an account? <a href="/signup/"> Sign Up </a>
            </div>
        </div>
    </div>
  </form>
{% endblock content %}

arrow/templates/arrow/showProducts.html
{% extends "base.html" %}
{% load i18n  static %}


{% block content %}
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
            <tr>
                <th>User Name</th>
                <th>Product Category</th>
                <th>Product Name</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.User.First_Name }} {{ product.User.Last_Name }}</td>
                <td>{{ product.Product_Category }}</td>
                <td>{{ product.Product_Name }}</td>
                <td>
                    <a href="/editProduct/{{ product.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
                </td>
                <td>
                    <a href="/deleteProduct/{{ product.id }}"><span class="glyphicon glyphicon-remove-circle" >Delete</span></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
        <br>
        <center><a href="/addProduct" class="btn btn-primary">Add New Record</a></center>
    <br>
    <br>
    <br>
    <br>
    <!--    Pagination   -->
    <center>
        {% if products.has_other_pages %}
        <ul class="pagination">
            {% if products.has_previous %}
                <li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if products.has_next %}
                <li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </center>

{% endblock content %}

arrow/templates/arrow/signup.html
{% extends "base.html" %}
{% load i18n  static %}


{% block content %}
    <form method="post">
        {% csrf_token %}
         <div class="container">
            <br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Sign Up</h3>
    </div>
  </div>
    {% for field in form %}
        <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
    {% endfor %}
             <br/>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
            </div>
              <br/>
            <br/>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                Already a User? <a href="/login/"> Log In </a>
            </div>
        </div>
  </div>
</form>
{% endblock content %}